export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
 export const USER_RESGITER_REQUEST="USER_RESGITER_REQUEST";
 export const USER_RESGITER_SUCCESS = "USER_RESGITER_SUCCESS";
 export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
